<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "devutils"
 *
 * Auto generated by Extension Builder 2017-09-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title'            => 'Development utilities',
	'description'      => 'Utility classes for development',
	'category'         => 'distribution',
	'author'           => 'Paweł Schwałkowski',
	'author_email'     => 'p.schwalkowski@gmail.com',
	'state'            => 'alpha',
	'internal'         => '',
	'uploadfolder'     => '0',
	'createDirs'       => '',
	'clearCacheOnLoad' => 0,
	'version'          => '1.0.0',
	'constraints'      => [
		'depends'   => [
			'typo3' => '8.7.0-8.7.99',
		],
		'conflicts' => [],
		'suggests'  => [],
	],
];
